AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sharp Lambda Layer

  A lambda layer containing the sharp library for nodejs

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sharp
      Description: A lambda layer containing the Sharp library for nodejs
      ContentUri: src/
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x
        - nodejs16.x

Outputs:
  LayerVersion:
    Description: Layer ARN Reference
    Value: !Ref SharedLayer

Metadata:
  AWS::ServerlessRepo::Application:
    Name: nodejs-sharp-lambda-layer
    Description: >
      Lambda-compatible build of the nodejs Sharp library
    Author: Paul Spencer
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.md
    ReadmeUrl: README.md
    Labels: ['layer', 'image', 'lambda', 'sharp']
    SemanticVersion: 0.31.1
    SourceCodeUrl: https://github.com/creativelayer/sharp-lambda-layer
